branch-defaults:
  main:
    environment: Flaskappcrypto-env
environment-defaults:
  Flaskappcrypto-env:
    branch: null
    repository: null
global:
  application_name: FlaskAppCrypto
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
